name: Build image

on:
  push:
    branches:
      - master
      - main
    paths:
      - .github/workflows/build-container.yaml

jobs:
  build-publish:
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        env:
          WIZ_CLIENT_ID: ${{ secrets.WIZ_CLIENT_ID }}
          WIZ_CLIENT_SECRET: ${{ secrets.WIZ_CLIENT_SECRET }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: make app/build-docker

      - name: download wiz-cli
        run: curl --silent -o wizcli https://wizcli.app.wiz.io/wizcli && chmod +x wizcli

      - name: authenticate to wiz
        run: ./wizcli auth --id $WIZ_CLIENT_ID --secret $WIZ_CLIENT_SECRET

      - name: Scan with Wiz-cli
        run: ./wizcli docker scan --image ghcr.io/arya-huma/simpleapp:0.5 --policy "$POLICY"

