name: Build image

on:
  push:
    branches:
      - master
    paths:
      - .github/workflows/build-container.yaml

jobs:
  build-publish:
    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Docker image
        run: make app/build-docker